syntax on

" Set line numbers
set number
" Set line numbers as relative
set relativenumber

set scrolloff=5

" Automatic intendation
set autoindent
set expandtab
set smartindent
" Make tabs as wide as 2 spaces
set tabstop=2
set softtabstop=2
set scrolloff=5

set shiftwidth=2

" Allow backspace in insert mode
set backspace=indent,eol,start

" Change mapleader
let mapleader=","
" Don’t add empty newlines at the end of files
set binary
set noeol

" Show invisible characters
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_

set directory=~/.local/share/vim/swap,/tmp
set undodir=~/.local/share/vim/undo,/tmp
set undofile

" Highlight searc
set hlsearch
" Ignore case on searches
set ignorecase
" Highlight dynamically as pattern is typed
set incsearch

" Always show status bar
set laststatus=2

" Don't reset cursor to the start of line when moving around
set nostartofline

set ruler

" Show dcument title in the window titlebar
set title



" Strip trailing whitespace (,ss)
function! StripWhitespace()
  let save_cursor = getpos(".")
  let old_query = getreg('/')
  :%s/\s\+$//e
  call setpos('.', save_cursor)
  call setreg('/', old_query)
endfunction
noremap <leader>ss :call StripWhitespace()<CR>
